version: "1"
services:
- type: web
  name: fbboost-project-v2
  runtime: python
  repo: https://github.com/hatungimanaadronis17-dotcom/fbboost-project-v2
  plan: free
  envVars:
  - key: DJANGO_SUPERUSER_PASSWORD
    sync: false
  region: frankfurt
  buildCommand: |
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
  startCommand: gunicorn fbboost.wsgi:application --log-file -
  autoDeployTrigger: "off"
#!/bin/bash
python manage.py makemigrations --noinput
python manage.py migrate --fake-initial   # ou --fake si besoin
python manage.py migrate
gunicorn ton_projet.wsgi   # ton commande start habituelle
